{"uuid": "1637da68-2649-4eca-be06-d8eb5ba25f4b", "children": ["3d6418fd-f61e-4a9b-937b-75d2ae4f6b27", "48e0d387-f9fd-42ca-9929-4cca7cc420c4", "d47be8be-2b12-49bc-9c50-184dc85d2cd9", "bbecc46a-5ff5-4d02-b13b-27571873b7fb", "cc8f123c-2133-43da-aa54-3ccedc1bfcf5", "c7dbb47d-f0ce-4912-8245-5677b8215269", "81238741-41f0-4298-b477-37e2a1c16245", "0c29f6b8-15b6-40a2-9fb4-73e3ad589913", "862c196a-3c72-4641-b6d4-5dd761a75a5a", "e7097735-57db-4ab3-89cb-16dcd33d4659"], "befores": [{"name": "assign_users_to_tenant_account", "status": "broken", "statusDetails": {"message": "hpe_ccs_automation_lib.session.core.exceptions.SessionException: Non Retryable error '403' for API 'GET https://mira-default-user-api.ccs.arubathena.com/ui-doorway/ui/v1/applications/provisions?application_id=92e14a96-82a1-431e-9d51-e6a575969627'\n", "trace": "  File \"/usr/local/lib/ccs-dev/poetry/venvs/hpe-authz-ft-9Ff49KU_-py3.8/lib/python3.8/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/ccs-dev/poetry/venvs/hpe-authz-ft-9Ff49KU_-py3.8/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/ccs-dev/poetry/venvs/hpe-authz-ft-9Ff49KU_-py3.8/lib/python3.8/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/dev/repo/ws/github.com/glcp/authz/tests/feature_test/testcases/conftest.py\", line 686, in assign_users_to_tenant_account\n    ui_helpers.provision_app_instance(\n  File \"/home/dev/repo/ws/github.com/glcp/authz/tests/feature_test/testcases/ui_helpers.py\", line 155, in provision_app_instance\n    provision = get_provisioned_application(session, application_id, region)\n  File \"/home/dev/repo/ws/github.com/glcp/authz/tests/feature_test/testcases/ui_helpers.py\", line 119, in get_provisioned_application\n    code, res = session.get_provisions({\"application_id\": application_id})\n  File \"/home/dev/repo/ws/github.com/glcp/authz/tests/feature_test/library/authz.py\", line 90, in decorated_func\n    code, res = func(*args, **kwargs)\n  File \"/home/dev/repo/ws/github.com/glcp/authz/tests/feature_test/library/authz.py\", line 458, in get_provisions\n    resp = self.get(url=url, params=payload, tuple_response=True,)\n  File \"/usr/local/lib/ccs-dev/poetry/venvs/hpe-authz-ft-9Ff49KU_-py3.8/lib/python3.8/site-packages/hpe_ccs_automation_lib/session/core/session.py\", line 85, in decorator\n    raise SessionException(\n"}, "start": 1692741620112, "stop": 1692741626071}], "start": 1692741620112, "stop": 1692741627938}